//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CombatScreen
{
	public virtual CombatManager _combatManager
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual void Draw(SpriteBatch spriteBatch)
	{
		throw new System.NotImplementedException();
	}

	public virtual void LoadContent()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UnloadContent()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Update(GameTime gameTime)
	{
		throw new System.NotImplementedException();
	}

}

