//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Stats
{
	public virtual int Health
	{
		get;
		set;
	}

	public virtual int Attack
	{
		get;
		set;
	}

	public virtual int Defense
	{
		get;
		set;
	}

	public virtual double CritChance
	{
		get;
		set;
	}

	public virtual int CritDamage
	{
		get;
		set;
	}

	public virtual double DamageReduction
	{
		get;
		set;
	}

	public virtual int Speed
	{
		get;
		set;
	}

	public Stats()
	{
	}

}

